### ISSUE TITLE
Value "./docker.sh: line 43: warning: command substitution: ignored null byte in input"

### ISSUE THREAD

**Issue by HrEL81** [digiapulssi/zabbix-monitoring-scripts#27]
Hello,
I always get this message

Ubuntu 18.04:

"netin"
./docker.sh 3c33dab3cdea29496602d622f7c89c783b59947b90e187e303244ee7dca149e2 netin
./docker.sh: line 43: warning: command substitution: ignored null byte in input
0

"MEMORY"
./docker.sh 3c33dab3cdea29496602d622f7c89c783b59947b90e187e303244ee7dca149e2 memory
./docker.sh: line 43: warning: command substitution: ignored null byte in input
93696000

but with up it works!?

./docker.sh 3c33dab3cdea29496602d622f7c89c783b59947b90e187e303244ee7dca149e2 up
1

Can you help me on this setup??

**Comment by sapajune** [comment]
Fixed in PR https://github.com/digiapulssi/zabbix-monitoring-scripts/pull/28, merged to master.
