### ISSUE TITLE
Value "" of type "string" is not suitable for value type "Numeric (unsigned)"

### ISSUE THREAD

**Issue by stefanodip** [digiapulssi/zabbix-monitoring-scripts#9]
Hi, 
I have set up, the scripts but i saw this error:

Value "" of type "string" is not suitable for value type "Numeric (unsigned)" on each db2Stat template field.

Can you help me on this setup??

**Comment by kompa3** [comment]
You can troubleshoot dbstat monitoring with a few ways:
* Test the item with `zabbix_agentd -t "db2stat.database_status[30,DATABASE_NAME]"` (replace DATABASE_NAME with a valid one)
* Test the script by manually running `/etc/zabbix/scripts/db2stat.pl 30 DATABASE_NAME "Database status"`
* Test db2 utility with zabbix user manually with `su -s /bin/bash -c "<path-to-db2dir>/bin/db2 get snapshot for database on <db>" zabbix`

One of them should print a detailed error message describing the problem.
